<a href="https://colab.research.google.com/github/thakshilaCodes/DS_LAB_01/blob/main/DSLab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.random.exponential(scale=2.0, size=(4, 4))

print(arr)


[[2.77594692 9.97631772 0.01257901 0.01453014]
 [2.13775759 1.14782948 0.89163981 0.14433465]
 [0.71333274 3.11409697 8.40629301 1.4268676 ]
 [3.45322485 3.16541791 0.08080782 1.24838716]]
